services:
  localstack:
    image: localstack/localstack:4.8.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb
    volumes:
      - ./localstack/init/ready.d:/etc/localstack/init/ready.d:ro
      - quick-mcp-poc-localstack:/var/lib/localstack

  nginx:
    image: nginx:1.28
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/templates:ro
    env_file:
      - ./nginx/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  quick-mcp-poc-localstack:
